site_name: standcup
repo_url: https://github.com/iamlucasvieira/standcup
site_url: https://iamlucasvieira.github.io/standcup
site_description: Table Football Tracker
site_author: Lucas Vieira dos Santos
edit_uri: edit/main/docs/
repo_name: iamlucasvieira/standcup
copyright: Maintained by <a href="https://iamlucasvieira.com">iamlucasvieira</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/standcup"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iamlucasvieira/standcup
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/standcup

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
